### ISSUE TITLE
Two colons given twice in task title give green highlight

### ISSUE THREAD

**Issue by xxddpp** [stacks-task-manager/stacks#107]
I use Stacks 1.7.0 and Windows 10 x64.

When I create a task and use two double colons in the task name (for example "Fix URL in HTTP::Get and HTTP::Post"), I get substring located between double colons ("Get and HTTP") highlighted in green and not displayed "as is". Double colons are also omitted.

**Comment by synapse** [comment]
Hey @xxddpp yes, the is because the task are by default using markdown for the text rendering, which in this case the `::text::` is used to highlight a text. It also accepts more colors like `:color:text:: -> you can see a small cheatsheet from the `View` menu. You can globally turn off md syntax from the Preferences -> Projects tab -> Tasks section

**Comment by xxddpp** [comment]
I don't want to turn markdown syntax globally because I use it sometimes. Maybe it will be better to implement backticks (`) in markdown syntax? It is the common markdown feature for the code - the text between two backticks is displayed as is in monospace font.

**Comment by synapse** [comment]
@xxddpp  Fixed it, will be available in 1.7.2
