### ISSUE TITLE
Cursor Position While Editing Task Title

### ISSUE THREAD

**Issue by doctopus** [stacks-task-manager/stacks#34]
The cursor appears at the end of the text when clicking on the Title or Description Box.

Can be reproduced by clicking any task to edit either the task title or the description.

The cursor should appear at the part of the text where it was clicked. Currently when clicking in either text or description no matter where you click the cursor appears at the end of the text. The purpose of clicking on the title or description is to make some changes. It would be handy and intuitive if the cursor appears where it was clicked instead of at the end of sentence. It would be intuitive while decreasing the need for one extra click to bring the cursor to where the user wants to edit.

Observed in MacOS 10.15.6

**Comment by synapse** [comment]
Hey @doctopus, this is kinda impossible more so with the release of the next version wherein the task detail modal window you'll be able to see both the title and the description rendered from markdown.

Clicking on the HTML render would not translate well to the textarea coordinates since the markdown syntax is much longer than the rendered HTML you're seeing. So interpreting the coordinates badly would still require 2 clicks.
