### ISSUE TITLE
Rename .board file

### ISSUE THREAD

**Issue by jokysatria** [stacks-task-manager/stacks#58]
**Is your feature request related to a problem? Please describe.**
I want to rename the board files for readability and easiness to identify. For example, from "d3a26568-5497-4e3c-ad5d-f7eb13ee1ec1.board" to "my board.board." 
![image](https://user-images.githubusercontent.com/69371378/98243084-055ad780-1fa0-11eb-98dc-087122eae422.png)

But every time I renamed it, I got an error, Stacks couldn't found my renamed board.
![image](https://user-images.githubusercontent.com/69371378/98242944-c9c00d80-1f9f-11eb-846a-4c2559efdb45.png)

**Describe the solution you'd like**
Stacks recognizes renamed board.

**Describe alternatives you've considered**
board. file also use board name as file name
![image](https://user-images.githubusercontent.com/69371378/98244873-ae0a3680-1fa2-11eb-8def-8b07f90ebf31.png)

**Comment by synapse** [comment]
Hey @jokysatria, there are several problems in renaming the board files which I'll try explaining below:

- since the offline version of Stacks could use a cloud service to sync its library this could cause some problems when there are multiple concurrent users involved. The cloud service may create a new file when one of the users renames the board. This could lead to problems when the other user is still changing the old file.
- for the online version of Stacks is strictly relying on the boards UUID to update the server database. Having on the client side 2 different naming/targeting systems may cause some problems (since version 0.8.0 we've enabled online accounts and use of the open-source server)
- in the next version we'll release a folder structure that will consent users to group boards in folders. Since there won't be a physical folder structure to do this could present some problems when there's a naming collision (different boards in a different folder with the same name)
- need to consider the fact that older clients need to convert everything without breaking anything (would need to create a middleware of sorts)

These are only a few problems on top of my head that could present some problems. I won't close this issue but will park it for the time being.

**Comment by jokysatria** [comment]
Understood, thank you. After reading your explanation, I had an idea for a workaround. I can use a folder for each board, then rename the folder.

**Comment by pidgeon777** [comment]
Or, eventually, the rename board feature could be added for the offline version. It would make more sense on this case, given that not everyone would share their boards with someone else, by choosing the offline way, instead.
